# This route enhancer config is not final
# But you can simply include it in your site configuration:
imports:
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserAccountDetail.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserAccountUpdate.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserDashboardDetail.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserDashboardUpdate.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserLoanHistoryDetail.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserPasswordUpdate.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserPinUpdate.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserSearchQueryDetail.yaml'
  - resource: 'EXT:slub_profile_account/Configuration/Routes/UserSearchQueryUpdate.yaml'
